-- Read the docs: https://rand0me.github.io/SolarVim/configuration/
-- Upstream LunarVim docs: https://www.lunarvim.org/docs/configuration
-- Example configs: https://github.com/LunarVim/starter.lvim
