# To run this file execute:
# docker build -f <Path to this file> <Path to SolarVim basedir> -t solarvim:local

FROM ubuntu:latest

# Set environment correctly
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:/root/.cargo/bin:/root/.npm-global/bin${PATH}"

# Copy in local directory
COPY --chown=root:root . /SolarVim

# Install dependencies and SolarVim
RUN apt update && \
  apt -y install sudo curl build-essential git fzf python3-dev python3-pip cargo && \
  curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && \
  apt update && \
  apt -y install nodejs && \
  apt clean && rm -rf /var/lib/apt/lists/* /tmp/* && \
  /SolarVim/utils/installer/install-neovim-from-release && \
  /SolarVim/utils/installer/install.sh --local --no-install-dependencies

# Setup SolarVim to run on startup
ENTRYPOINT ["/bin/bash"]
CMD ["solarvim"]

# vim: ft=dockerfile:
